# https://github.com/marketplace/actions/release-drafter#configuration
template: |
  ## Changes from $PREVIOUS_TAG
  $CHANGES
  
  ## Contributors
  $CONTRIBUTORS
name-template: '$RESOLVED_VERSION xxx Update [Alpha|Beta]'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🌈 New Platform!'
    labels:
      - 'Type/Platform'
  - title: '🚀 Features'
    labels:
      - 'Type/Enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Type/Bug'
  - title: '🧰 Maintenance'
    label: 'Type/Housekeeping'
# Extra line before $BODY or markdown on the first line of $BODY will be interpreted as plain text
change-template: |
  <details><summary>$TITLE (#$NUMBER) @$AUTHOR</summary>
  
  $BODY
  </details>
no-changes-template: '* (No changes)'
prerelease: true
version-resolver:
  major:
    labels:
      - 'Version/Major'
  minor:
    labels:
      - 'Version/Minor'
  patch:
    labels:
      - 'Version/Patch'
  default: patch
exclude-labels:
  - 'Version/None'
replacers:
  - search: '/<details><summary>((?:(?!<details>|<summary>).)+)<\/summary>\s*<\/details>/g'
    replace: '- $1'
